### ISSUE TITLE
some test case has error 

### ISSUE THREAD

**Issue by rubi1541** [bostrom/text-to-image#20]
setting
* os: mac 15.10.3
* vm: docker
* image: nikolaik/python-nodejs:python3.8-nodejs12

step
1. git clone
2. npm install
3. npm test

I want to know if it is my own problem or if it is the same for others.

```
root@95e18da61026:/usr/app# npm test

> text-to-image@2.2.0 test /usr/app
> jest --coverage

 FAIL  test/textToImage.test.js (7.585s)
  ● the text-to-image generator › should default to a black text color

    expect(received).toEqual(expected) // deep equality

    Expected: 220
    Received: 320

      173 | 
      174 |     expect(dimensions.width).toEqual(WIDTH);
    > 175 |     expect(dimensions.height).toEqual(HEIGHT);
          |                               ^
      176 | 
      177 |     const imageData = fs.readFileSync(images[0]);
      178 |     const image = await readImageData(imageData);

      at Object.<anonymous> (test/textToImage.test.js:175:31)

  ● the text-to-image generator › should use the text color specified

    expect(received).toEqual(expected) // deep equality

    Expected: 220
    Received: 320

      202 | 
      203 |     expect(dimensions.width).toEqual(WIDTH);
    > 204 |     expect(dimensions.height).toEqual(HEIGHT);
          |                               ^
      205 | 
      206 |     const imageData = fs.readFileSync(images[0]);
      207 |     const image = await readImageData(imageData);

      at Object.<anonymous> (test/textToImage.test.js:204:31)

  ● the text-to-image generator › should support aligning text

    expect(received).not.toEqual(expected) // deep equality

    Expected: not 255

      274 | 
      275 |     expect(centerAlignData.frames[0].data[400 * 19 * 4 - 13 * 4]).toEqual(0xff);
    > 276 |     expect(centerAlignData.frames[0].data[400 * 19 * 4 - 206 * 4]).not.toEqual(0xff);
          |                                                                        ^
      277 |     expect(centerAlignData.frames[0].data[400 * 19 * 4 + 13 * 4]).toEqual(0xff);
      278 | 
      279 |     expect(leftAlignData.frames[0].data[400 * 19 * 4 - 13 * 4]).toEqual(0xff);

      at Object.<anonymous> (test/textToImage.test.js:276:72)

 PASS  test/helpers/readImageData.test.js
-------------------|---------|----------|---------|---------|-------------------
File               | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-------------------|---------|----------|---------|---------|-------------------
All files          |     100 |      100 |     100 |     100 |                   
 lib               |     100 |      100 |     100 |     100 |                   
  textToImage.js   |     100 |      100 |     100 |     100 |                   
 test/helpers      |     100 |      100 |     100 |     100 |                   
  extractColors.js |     100 |      100 |     100 |     100 |                   
  readImageData.js |     100 |      100 |     100 |     100 |                   
-------------------|---------|----------|---------|---------|-------------------

Test Suites: 1 failed, 1 passed, 2 total
Tests:       3 failed, 13 passed, 16 total
Snapshots:   0 total
Time:        16.199s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
root@95e18da61026:/usr/app# 
```

**Comment by bostrom** [comment]
Thanks for the report. I was able to reproduce your case. It seems that for some reason the text in the test overflows on an additional line, making the resulting image taller than it should be. I don't know why this happens in certain environments, but a quick fix could be to shorten the text in the test slightly to prevent it from flowing over. 

Just out of curiosity, why are you concerned about the tests failing? :)
